### PR TITLE
Convert const West to East const format

### PR DESCRIPTION
**Pull request by biddisco**
Convert all files and add simple script for making conversion using

sed -i -E 's/const ([a-zA-Z0-9_<>,:]+)&/\1 const\&/g'

NB. the character set includes alphanumeric as well as "_<>,:" to allow const std::vector<std::vector, allocator> expressions to be correctly detected. Other might be needed for more complex parameter lists.

### CODE REVIEW

**Comment by biddisco** [comment]
if approved, this could also be added to git hooks - perhaps clang-format supports this already ...

**Comment by biddisco** [comment]
> if approved, this could also be added to git hooks - perhaps clang-format supports this already ...

from clang-format-14 onwards
`QualifierAlignment: Right`

**Comment by biddisco** [comment]
closing because it would be easier to add a clang-format and let nature take its course y reformatting files each time they are changed/committed

**Comment by biddisco** [comment]
reopening with clang format change instead of script

**Review by msimberg — CHANGES_REQUESTED** [review]
Very nice, thank you!

Can you change the signature for `pika::start` in the docs to match east-const: https://github.com/pika-org/pika/blob/main/docs/api.rst#pikainithpp? The documentation build is failing because the docs signature doesn't the updated signature in the code anymore.

**Review by msimberg — APPROVED** [review]

**Pull request merged**
