### PR TITLE
Clean up `functional` module

### PR DESCRIPTION
**Pull request by msimberg**
Part of #16. Moves most functionality into detail once again. Note that I have _not_ done anything about #265 here. At least using `std::invoke` did increase the size of debug symbols measurably so we'll have to revisit that to see if it's worth the tradeoff.

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
