### PR TITLE
Make posix utility guards consistent in Boost coroutines implementation

### PR DESCRIPTION
**Pull request by msimberg**
This should fix problems seen on Apple M1/M2 systems.

### CODE REVIEW

**Comment by albestro** [comment]
Tested this branch PR on an Apple M2.

```console
➜  dla-future git:(alby/permute-dist) ✗ spack -e . find -v pika
==> In environment /Users/ialberto/workspace/repos/dla-future
==> Root specs
dla-future  build_type=Debug

==> Installed packages
-- darwin-ventura-armv8.5a / clang@12.0.1 -----------------------
pika@git.fix-generic-context-coroutines-posix-stack-2=main~apex~cuda~examples+generic_coroutines~ipo+mpi~rocm~stdexec~tracy build_system=cmake build_type=Debug cxxstd=17 generator=ninja malloc=mimalloc
```

I built dla-future and passed all tests 🍾 

```console
...
100% tests passed, 0 tests failed out of 59

Label Time Summary:
RANK_1    =  25.61 sec*proc (20 tests)
RANK_2    =   2.21 sec*proc (5 tests)
RANK_4    =   2.09 sec*proc (7 tests)
RANK_6    =  93.51 sec*proc (27 tests)

Total Test time (real) = 123.43 sec
```

Thanks!

**Review by albestro — APPROVED** [review]

**Review by rasolca — APPROVED** [review]

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
> should we enable the github/macos_arm64/debug CI in this PR too?

Nope, it needs to be set up again at the new offices...

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
