### PR TITLE
Remove Vc support

### LINKED ISSUE #190: Remove Vc
Vc is only in maintenance mode. We can deprecate it as the `std::experimental::simd` support is in place. This would require gcc-11.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #190.

### CODE REVIEW

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors ping

**Comment by msimberg** [comment]
bors try

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Pull request merged**
