### PR TITLE
Update the `nth_element` test to check for corner cases

### PR DESCRIPTION
**Pull request by msimberg**
The follow-up to #412 for the non-ranges version.

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by aurianer** [comment]
bors try

**Comment by aurianer** [comment]
bors try

**Comment by aurianer** [comment]
bors try-

**Comment by aurianer** [comment]
bors try

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors cancel

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
