### PR TITLE
Change builtin detection to use `__has_builtin` instead of using configuration tests

### PR DESCRIPTION
**Pull request by msimberg**
The configuration tests for the various builtins are difficult to maintain. We hit another case when building CP2K where pika was built with `hipcc` and detected that it had `__make_integer_seq` (since it's clang) and when compiling CP2K with gcc it expected to have `__make_integer_seq` but failed because it has `__integer_pack` instead.

See https://godbolt.org/z/4ej7hnbTK for an example.

Since it's unreasonable to expect everyone to really use the same compiler (it's recommended but not a must) I've changed the detection to be at the use site of the builtins using `#if defined(__has_builtin) && __has_builtin(__integer_pack)`. This is in my opinion at least as simple where they are used and avoids detecting them wrongly if the consumer's compiler is different from the one used to compiler pika itself.

I've bumped the priority of #333 as well since it's an alternative "solution" to the same problem (however, only partial).

### CODE REVIEW

**Comment by msimberg** [comment]
The variant implementation uses exactly this method as well, by the way.

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by aurianer** [comment]
bors merge

**Comment by aurianer** [comment]
bors merge-

**Comment by aurianer** [comment]
sorry my page was not up to date and didn't show the conflict on your PR

**Comment by msimberg** [comment]
> sorry my page was not up to date and didn't show the conflict on your PR

No need to apologize, all good.

bors merge

**Comment by msimberg** [comment]
bors cancel

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
