### PR TITLE
An uninitialized variable was being used for setting up pools

### PR DESCRIPTION
**Pull request by biddisco**
The affinity data value of pus_needed should be returned instead.

### CODE REVIEW

**Review by msimberg — APPROVED** [review]
Nice, thanks! Where did this come up/get triggered?

**Comment by biddisco** [comment]
> Nice, thanks! Where did this come up/get triggered?

Threads assigned to pools did not match what I put in `pika:threads=`

**Comment by msimberg** [comment]
test cscs

**Comment by msimberg** [comment]
launch perftests

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
