### PR TITLE
Require Jenkins jobs for bors merges

### LINKED ISSUE #31: Use bors for all CI
This would reduce duplicate and unnecessary builds. This requires:
- CI that is stable for all enabled builds
- Jenkins sets the commit status on all builds

### PR DESCRIPTION
**Pull request by msimberg**
Draft. Requires #23 before this makes sense. Testing that the Jenkins commit statuses etc. work correctly.

Fixes #31.

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
The statuses *don't* seem to be set correctly so this needs some investigation.

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
Statuses seem to at least be set now correctly. The CDash project is still missing so Jenkins status URLs are still broken.

I've made almost everything a required bors check now, with the exception of the perftests since they're not 100% reliable and the spellchecker which is anyway more of a guideline. Conversely I've removed almost everything from building automatically on pushes and `bors try` should be used instead to trigger CI jobs. However, I've kept the GitHub actions linux debug job as a quick check (it builds and runs the examples in 3 minutes) and the static checks from CircleCI to run automatically on pushes since they are all quick to run.

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
I would wait a week or so to see if #180 fixes the most frequent failures on Jenkins, and if it does I would go ahead with this one in its current state. That is everything required except:
- `gcc-10-apex`
- CircleCI `tests.unit`
since those still fail far too often for this to be useful.

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
Doing a few runs just to see how good/bad the situation is...

bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
I'd say we try this. We can always reduce the requirements again and/or merge manually.

**Review by aurianer — APPROVED** [review]
LGTM thanks!
So if I understood well you commented out the failing tests for now and we will reintegrate them when we fixed them right?

**Comment by msimberg** [comment]
> LGTM thanks! So if I understood well you commented out the failing tests for now and we will reintegrate them when we fixed them right?

I've commented out the configurations that frequently have failing tests (meaning apex and the unit tests on CircleCI), but the tests themselves are still enabled. So we may still get some "false positives" with flaky tests preventing merging, but it's hopefully not too bad.

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
