### PR TITLE
Update the CMake MPI setup

### PR DESCRIPTION
**Pull request by aurianer**

### CODE REVIEW

**Review by msimberg — APPROVED** [review]
Thanks! Since we don't currently have any CI configurations with MPI did you test this at least on one system?

**Comment by aurianer** [comment]
I tested the PR that was opened against the hpx repo but now that I tested this one after the daint upgrade there is a segfault that I have to investigate

**Comment by aurianer** [comment]
Now tested and works :D

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
