### PR TITLE
Replace typename std::decay by std::decay_t

### PR DESCRIPTION
**Pull request by aurianer**
Help with the cleanup

### CODE REVIEW

**Comment by aurianer** [comment]
bors try

**Review by msimberg — APPROVED** [review]
Excellent, thank you!

Did you do this with a script or manually?

**Comment by aurianer** [comment]
script haha I don't have the patience to do that manually x)

**Comment by aurianer** [comment]
bors try

**Comment by aurianer** [comment]
bors try

**Comment by aurianer** [comment]
bors try

**Comment by aurianer** [comment]
bors try

**Comment by aurianer** [comment]
bors try-

**Comment by aurianer** [comment]
bors try

**Comment by aurianer** [comment]
bors merge

**Pull request merged**
