### PR TITLE
compiler_fence: fix PPC assembler for Darwin, unbreak the build

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://github.com/pika-org/pika/issues/577

Existing one-size-fits-all PPC code breaks the build on Darwin. PR fixes it.
Also, ppc64 case should be accommodated.

## Checklist

Not all points below apply to all pull requests.

- [ ] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.
- [ ] I have changed the CI configurations and made a corresponding change to bors.toml.

### CODE REVIEW

**Comment by msimberg** [comment]
launch perftests

**Comment by msimberg** [comment]
bors try

**Review by msimberg — APPROVED** [review]
Thanks @barracuda156!

**Comment by barracuda156** [comment]
I ran header tests, 100% pass:
```
100% tests passed, 0 tests failed out of 461

Total Test time (real) = 12173.61 sec
```
(Takes forever, this is ppc32 via Rosetta.)

**Comment by barracuda156** [comment]
I ran header tests, 100% pass:
```
100% tests passed, 0 tests failed out of 461

Total Test time (real) = 12173.61 sec
```
(Takes forever, this is ppc32 via Rosetta.)

**Comment by msimberg** [comment]
> I ran header tests, 100% pass:
> 
> ```
> 100% tests passed, 0 tests failed out of 461
> 
> Total Test time (real) = 12173.61 sec
> ```
> 
> (Takes forever, this is ppc32 via Rosetta.)

Better than nothing! I don't have very high hopes for the tests themselves, but it's of course nice if they run (I'm not expecting you to check that or fix anything).

**Comment by msimberg** [comment]
bors merge

**Comment by barracuda156** [comment]
> Better than nothing! I don't have very high hopes for the tests themselves, but it's of course nice if they run (I'm not expecting you to check that or fix anything).

I will try running the whole suite a bit later, but not in emulation. G5 Quad should be good with that.

**Comment by msimberg** [comment]
bors merge

**Comment by barracuda156** [comment]
> Build failed:
>   * [github/macos/debug](https://github.com/pika-org/pika/actions/runs/4044910815/jobs/6955660003)

* Reported failure in one of the tests cannot be caused by my patch, since buildbot obviously does not run MacOS PowerPC.

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
