### PR TITLE
Move `sync_wait` to `pika::this_thread` namespace

### PR DESCRIPTION
**Pull request by msimberg**
P2300 defines `sync_wait` in `std::this_thread`. This moves our `sync_wait` to `pika::this_thread` to be analogous to the proposed one.

### CODE REVIEW

**Comment by msimberg** [comment]
test cscs

**Comment by msimberg** [comment]
test cscs

**Comment by msimberg** [comment]
test cscs

**Comment by msimberg** [comment]
test cscs

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
This will be a breaking change for DLA-Future by the way.

**Pull request merged**
