### PR TITLE
Set spack user config and cache path only if not set

### PR DESCRIPTION
**Pull request by aurianer**
Makes it easier to `source env-common.sh` for testing CI

### CODE REVIEW

**Comment by aurianer** [comment]
bors try

**Comment by aurianer** [comment]
bors try

**Review by msimberg — APPROVED** [review]
Thanks!

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
