### PR TITLE
Add workaround to ensure `PIKA_PROCESS_MASK` is respected

### LINKED ISSUE #743: Make sure `PIKA_PROCESS_MASK` is actually honored by the runtime configuration
https://github.com/pika-org/pika/pull/739#discussion_r1295965920

Also make sure to add documentation about `PIKA_PROCESS_MASK`.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #743. However, this only special cases the handling for `PIKA_PROCESS_MASK` and doesn't fix the behaviour for any other configuration options. The proper fix would require doing #745. This also adds an additional check for empty process masks when set through `PIKA_PROCESS_MASK` or `--pika:process-mask` to give a better error message when the mask is empty.

### CODE REVIEW

**Review by RMeli — APPROVED** [review]
Thanks @msimberg! Is it worth adding it to the documentation?

**Comment by msimberg** [comment]
> Thanks @msimberg! Is it worth adding it to the documentation?

Yes, thanks for the reminder!

**Comment by msimberg** [comment]
@RMeli added documentation, would you mind checking if the explanation is clear to you?

In theory `--pika:ignore-process-mask` could get the same treatment with an environment variable workaround. @RMeli do you think you will be needing `PIKA_IGNORE_PROCESS_MASK` at some point soon, or do you think we can wait with a workaround to see if we can do #745 before the workaround?

**Review by RMeli — APPROVED** [review]
Thanks @msimberg. Documentation is clear, and specifies the precedence which is great. LGTM!

> or do you think we can wait with a workaround to see if we can do https://github.com/pika-org/pika/issues/745 before the workaround?

I think we can wait and eventually adapt if the need arises.

**Pull request merged**
