### PR TITLE
Clean up `async_mpi` module

### PR DESCRIPTION
**Pull request by msimberg**
Part of #16.

- Moves helpers into `detail`
- Removes the MPI executor
- ADL-isolates the `transform_mpi` sender
- Adds support for compiling `async_mpi` with the P2300 reference implementation
- Enables C++20 and the P2300 reference implementation on CircleCI for testing with MPI enabled (ideally we'd have both, so we may have to come back to this one before the next release or before this is merged)

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
