### PR TITLE
Move ccache directory to `jenkssl` scratch in Jenkins jobs

### LINKED ISSUE #299: Move Jenkins CI's ccache and spack cache directories to `jenkssl` user's scratch directory

### PR DESCRIPTION
**Pull request by msimberg**
Fixes half of #299.

I've also moved the `SPACK_ROOT` definition to `env-common.sh` to 1. have it only in one place and 2. to have it together with the rest of the environment. It doesn't actually need to be set in the `Jenkinsfile`, unlike the GitHub credentials.

Edit: I updated this to only move the ccache directory for the moment. The spack user cache directory seems to be a bit more complicated...

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
bors try

**Comment by aurianer** [comment]
bors merge

**Pull request merged**
