### PR TITLE
Clean up debugging module

### PR DESCRIPTION
**Pull request by msimberg**
Part of #16.

I've kept the sub-namespace `pika::debug` and put everything in `pika::debug::detail` to avoid polluting `pika::detail` with short names like `ptr`.

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Review by aurianer — APPROVED** [review]
LGTM thanks a lot!

**Comment by aurianer** [comment]
bors merge

**Pull request merged**
