### PR TITLE
Remove restriction to call `pika::finalize` on a pika thread

### LINKED ISSUE #349: Attempt to lift restriction of running `pika::finalize` on a pika thread
I think this is no longer a relevant restriction (after the runtime pointer moved to a global static), but it needs to be tested. This would simplify finalizing the runtime in "fork-join" style code.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #349.

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
