### PR TITLE
Enable warnings as errors in all CI configurations

### LINKED ISSUE #198: Check that warnings-as-errors is enabled on all CI configurations
...where possible. I noticed we at least have warnings enabled on the HIP configuration, but don't make them errors: https://github.com/pika-org/pika/runs/6075864287.

### PR DESCRIPTION
**Pull request by aurianer**
Attempt to fix #198

### CODE REVIEW

**Comment by aurianer** [comment]
bors try

**Comment by aurianer** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Review by msimberg — APPROVED** [review]

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
