### PR TITLE
Replace THREADS_PER_LOCALITY with THREADS

### LINKED ISSUE #33: Rename `THREADS_PER_LOCALITY` test option to just `THREADS`
The locality concept has little meaning with distributed functionality removed.

### PR DESCRIPTION
**Pull request by aurianer**
Fixes #33

### CODE REVIEW

**Comment by aurianer** [comment]
tests cscs

**Comment by msimberg** [comment]
test cscs

**Review by msimberg — APPROVED** [review]
Thanks!

**Comment by msimberg** [comment]
Could you fix the CMake formatting please?

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
