### PR TITLE
Move testing module to a separate library

### LINKED ISSUE #20: Move testing module into separate library
The testing functionality should not be exposed to users of `pika`.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #20.

Still a bit rough around the edges and not fully tested.
- [x] Should it be a shared or static library? I think shared is fine.
- [x] Naming/location (i.e. directory)? Currently under the root in `testing`.
- [x] This removes the ability to attach a debugger on test failures since it creates an annoying dependency between `init_runtime` and `testing`. This only worked if the runtime was actually started, not for all tests so I decided to remove the functionality. Is someone going to miss it?

### CODE REVIEW

**Comment by msimberg** [comment]
A bit less rough around the edges now and ready for review, but this is low priority compared to other PRs.

**Comment by msimberg** [comment]
test cscs

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
test cscs

**Comment by msimberg** [comment]
test cscs

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
Would've needed #31 now :disappointed: https://cdash.cscs.ch/viewBuildError.php?buildid=4349. Fixed in https://github.com/pika-org/pika/commit/eb5e51f5de3242545c3137f92ece86156a689bd9.

**Pull request merged**
