### PR TITLE
Clean up `algorithms` module part 1

### PR DESCRIPTION
**Pull request by msimberg**
Part of #16. Moves some functionality in `algorithms` into detail, but not all. Concatenates nested namespaces (and I found out about https://clang.llvm.org/extra/clang-tidy/checks/modernize/concat-nested-namespaces.html, which I think we can enable in the clang-tidy config). There's so much to change in the algorithms module that I'm leaving this PR in the current stage except for build errors and continuing in a separate PR once this is in.

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Review by aurianer — APPROVED** [review]
LGTM thanks! It was a big PR, I hope I didn't let anything pass

**Comment by msimberg** [comment]
> LGTM thanks! It was a big PR, I hope I didn't let anything pass

Thank you for looking! I realized a bit too late how big this became, but I'll try to do the rest of the algoriothms module in smaller parts.

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors cancel

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
