### PR TITLE
Use `MPI_Init_thread` in `algorithm_transform_mpi` test

### PR DESCRIPTION
**Pull request by msimberg**
It's not really clear if we've just gotten lucky or if something else was going on in that test, but we should be initializing MPI with `MPI_THREAD_MULTIPLE` to be on the safe side.

Thank you @RMeli for noticing this.

### CODE REVIEW

**Comment by msimberg** [comment]
@biddisco it occurs to me that `get_preferred_thread_mode` is near impossible to use in a meaningful way. Ideally MPI should be initialized before pika, but if one uses `get_preferred_thread_mode` before pika has been initialized, it won't return the correct value (configuration options and command line options are not taken into account yet at that point) except by chance. If one tries to use it after pika has been initialized, it's too late since MPI should already have been initialized for pika by that point. Is this accurate?

**Comment by biddisco** [comment]
> @biddisco it occurs to me that `get_preferred_thread_mode` is near impossible to use in a meaningful way. Ideally MPI should be initialized before pika, but if one uses `get_preferred_thread_mode` before pika has been initialized, it won't return the correct value (configuration options and command line options are not taken into account yet at that point) except by chance. If one tries to use it after pika has been initialized, it's too late since MPI should already have been initialized for pika by that point. Is this accurate?

I'm sure I replied to this already somewhere ... 
Correct. If ENV vars are used to set completion mode, pool status etc, then there is no requirement to init pika before the internal flags are set correctly. This is an unfortunate consequence of us adding support for command-line vars that I had forgotten about.

Also, it would be nice to use our error checking init in mpi:environment
```
    int provided;
    pika::mpi::detail::environment::init(
        &argc, &argv, MPI_THREAD_MULTIPLE, MPI_THREAD_MULTIPLE, provided);
``` 
but that has been moved into detail namespace so should not be in public facing code.

**Comment by biddisco** [comment]
```
    int provided, preferred = mpix::get_preferred_thread_mode();
    pika::mpi::detail::environment::init(
        &argc, &argv, preferred, preferred, provided);
```
would be the original way of doing it using ENV vars.

**Comment by biddisco** [comment]
I will include this fix in #1267 and this can be closed.

**Comment by msimberg** [comment]
This needs further investigation. The test which now uses `MPI_Init_thread` now fails/times out depending on the MPI mode.

**Comment by biddisco** [comment]
from slack 
```Does it look like whitelisting may be enough? = naive suggestion for "not sure what to do", i.e. can we ignore the warnings if they are warnings from inside mpich and we're not doing anything wrong?```

If we do not register an error handler, mpich does not hang on exit, if we do register an error handler, but don't trigger any errors, mpich doesn't hang on exit, if we register the handler, do trigger errors, but don't use exceptions, then it still hangs.
I therefore conclude that the problem lies inside mpich handling of errors when an error handler is registered.
This issue https://github.com/pmodels/mpich/issues/268 in mpich appears related, but was "fixed" many years ago.  

I suggest we mark this test as problematic in CI and file an issue with mpich with a reproducer (which I will attempt to create right away)

**Comment by msimberg** [comment]
> I suggest we mark this test as problematic in CI and file an issue with mpich with a reproducer (which I will attempt to create right away)

I will have a few gos at suppressing the warnings/errors as `algorithm_transform_mpi` is one of the main tests for the MPI functionality and completely ignoring it for sanitizer testing would be a shame. Worst case if we can't suppress the warnings is that I separate the failing parts to a different test that can be ignored on its own so that we don't completely lose sanitizer testing on this test.

**Comment by biddisco** [comment]
I've filed an issue with mpich with a reproducer https://github.com/pmodels/mpich/issues/7187 which shows there is a problem, though the reproducer does not hang on exit as our tests do. I will wait for comments on the reproducer before investigating further.

**Comment by msimberg** [comment]
> I was expecting to see changes to the thread sanitizer workflow - but here there are changes to the ubsan github workflow. I don't really understand all the syntx of the yaml workfow files, so I trust this is as expected ...

There are no changes expected to the thread sanitizer workflow. It stays with MPICH since OpenMPI completely fails to initialize with thread sanitizer loaded.

The ubsan workflow you're referring to (which includes address and leak sanitizer) was changed from MPICH to OpenMPI, so that we can keep the error handling tests enabled there (which would otherwise be disabled with MPICH now, as in the thread sanitizer workflow).

**Comment by biddisco** [comment]
hmmm. ok, it was the thread sanitizer check that was failing for me, so I assumed it needed to be switched from openmpi to mpich, but since you removed a bunch of commits, maybe this was actually the original default and now it is as it used to be

**Comment by msimberg** [comment]
> hmmm. ok, it was the thread sanitizer check that was failing for me, so I assumed it needed to be switched from openmpi to mpich, but since you removed a bunch of commits, maybe this was actually the original default and now it is as it used to be

Exactly, MPICH is already being used for both tsan and asan on main (so I removed the change in this PR to change from MPICH to OpenMPI which wasn't useful for tsan).

**Review by biddisco — APPROVED** [review]
LGTM, lets see if dashboard passes tests

**Pull request merged**
