### PR TITLE
Add simple `boost::ranges::irange` replacement

### PR DESCRIPTION
**Pull request by msimberg**
Part of #12. Adds a simple replacement for `boost::ranges::irange` (`pika::detail::irange` and `pika::detail::strided_irange`).

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors cancel

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors cancel

**Comment by msimberg** [comment]
bors try

**Review by rasolca — APPROVED** [review]

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
