### PR TITLE
Remove function_nonser from pika, replaced by function

### PR DESCRIPTION
**Pull request by aurianer**
Following #145, function_nonser can be removed since the default function is now non serializable.

### CODE REVIEW

**Comment by aurianer** [comment]
test cscs

**Comment by aurianer** [comment]
launch perftests

**Review by msimberg — APPROVED** [review]
Approved modulo formatting. Thanks!

**Comment by aurianer** [comment]
I just rebased, it was clashing with the ensure_started PR, should be good to go now

**Comment by aurianer** [comment]
test cscs

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
