### PR TITLE
Update the reference of the stream bench for fork_join_executor

### LINKED ISSUE #84: Update performance test references
The current references seem to be somewhat too strict. Alternatively, can we slightly relax the criteria (without missing performance regressions).

### PR DESCRIPTION
**Pull request by aurianer**
Maybe fixes #84

### CODE REVIEW

**Comment by msimberg** [comment]
launch perftests

**Comment by aurianer** [comment]
launch perftests

**Comment by aurianer** [comment]
The stream for the fork_join_executor looks at least more stable, will have a look at the parallel_executor now

**Comment by msimberg** [comment]
launch perftests

**Comment by msimberg** [comment]
Should we go ahead with this one as it is or should we still also update the foreach reference? It just about failed once, and failed once badly, but I'm not sure if the latter was with or without #91?

**Comment by aurianer** [comment]
I think we can go ahead with it like that cause looks like the last run passed, if it fails more often I can still update it in a separate PR

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
