### PR TITLE
Add `scoped_finalize` helper struct for calling `pika::finalize`

### LINKED ISSUE #94: Add RAII "finalizer" helper
Add an RAII helper which calls `pika::finalize` on destruction. See https://github.com/eth-cscs/DLA-Future/issues/367.

```
struct scoped_finalizer {
    ~scoped_finalizer() { pika::finalize(); }
};
```

would probably be enough.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #94.

Somewhat quickly put together RAII helper. I don't think there's so much more to it though...

- [x] `scoped_finalize` or `scoped_finalizer` (or something else)?
- [x] any other useful tests that can be added? nothing I can think of now...

## Checklist

Not all points below apply to all pull requests.

- [x] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

### CODE REVIEW

**Comment by msimberg** [comment]
@albestro, @rasolca, @teonnik comments welcome.

**Comment by msimberg** [comment]
test cscs

**Review by teonnik — APPROVED** [review]
LGTM!

**Review by albestro — APPROVED** [review]
It looks like a nice improvement! Thanks!

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
