### PR TITLE
Remove `operator|` overloads for `sync_wait` and `start_detached`

### LINKED ISSUE #329: Remove `operator|` overload for `pika::this_thread::experimental::sync_wait`
See https://github.com/eth-cscs/DLA-Future/issues/596.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #329 .

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
