### PR TITLE
Add PR numbers to CDash build names for `staging` and `trying` branches

### LINKED ISSUE #311: Add commit message/PR numbers to bors trying/staging Jenkins CI job names

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #311.

In progress, testing changes.

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Comment by biddisco** [comment]
bors try

**Comment by msimberg** [comment]
I'm merging this as this seems to be working. However, @aurianer, please have a look afterwards as well if you have ideas for improvements or changes to the format. We can easily update it to a different format.

bors merge

**Comment by msimberg** [comment]
bors merge

**Comment by aurianer** [comment]
Thanks a lot for this!

**Pull request merged**
